{
 "title": "Jitsi Control",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Jitsi Control\n\nOverview of key metrics for all Jitsi Instances hosted on this server."
   }
  },
  {
   "title": "Uptime per Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-container_start_time_seconds{name=~\"jitsi.*web.*\"})/60",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Conferences",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(total_conferences_completed) by (job)"
    }
   ]
  },
  {
   "title": "Conferences",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "conferences", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "participants", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Largest Active Conference",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "largest_conference" }
   ]
  },
  {
   "title": "Avg. Conference Length (min)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(total_conference_seconds) / 60"
    }
   ]
  },
  {
   "title": "Total Active Conferences",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(conferences) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total Active Participants",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(participants) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Videochannels",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(videochannels) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Loss Ratio (time-based)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(total_loss_controlled_participant_seconds / total_conference_seconds)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"jitsi.*\"}[1m]) / 1024)"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{name=~\"jitsi.*\"}[1m]) / 1024)"
    }
   ]
  },
  {
   "title": "Threads Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "threads", "legendFormat": "{{job}}" }
   ]
  }
 ]
}