[srv01_host]
# Main host
srv01
# Tenants
srv01_seydell_org 
srv01_be
#srv01_dev_seydell_org

[srv01_host:vars]
ansible_host=91.132.144.119
ansible_ssh_host=91.132.144.119

[common]
srv01

[docker]
srv01

[traefik]
srv01

#[nextcloud]
#srv01_seydell_org

[jitsi_docker]
srv01_seydell_org
srv01_be
#srv01_dev_seydell_org

#[collabora]
#srv01_seydell_org

#[onlyoffice]
#srv01_seydell_org

#[cryptpad]
#srv01_seydell_org

[grafana_docker]
srv01