---
# Deploy all the things

- import_playbook: playbooks/common.yml
- import_playbook: playbooks/docker.yml
- import_playbook: playbooks/traefik.yml
- import_playbook: playbooks/nextcloud.yml
- import_playbook: playbooks/collabora-online.yml
- import_playbook: playbooks/jitsi.yml
- import_playbook: playbooks/cryptpad.yml
